import { invoke } from "@tauri-apps/api/core";
import type { Asset, AssetSearchRequest } from "../types/asset";
export type Dimension = "usage" | "subject" | "action" | "style" | "general";
export const DIMENSIONS: Record<Dimension, string> = { usage: "用途", subject: "对象", action: "动作", style: "风格", general: "普通标签" };
export type DiscoveryFilter = { directory_path: string | null; recursive: boolean; tag_ids: number[]; excluded_tag_ids: number[]; unclassified: boolean };
export const defaultDiscovery = (): DiscoveryFilter => ({ directory_path: null, recursive: true, tag_ids: [], excluded_tag_ids: [], unclassified: false });
export type FacetTag = { id: number; name: string; color: string; dimension: Dimension; asset_count: number };
export type IndexedDirectory = { path: string; count: number };
export type ClassificationRule = { id: number; name: string; field: "directory" | "filename"; pattern: string; tag_id: number };
export type RuleCandidate = { asset: Asset; reason: string };
export type ClassificationBatch = { id: number; rule_name: string; created_at: string; added_count: number; undone: boolean };
export const listIndexedDirectories = (folderId: number) => invoke<IndexedDirectory[]>("list_indexed_directories", { folderId });
export const listFacetTags = (request: AssetSearchRequest) => invoke<FacetTag[]>("list_facet_tags", { request });
export const saveCategoryTag = (name: string, dimension: Dimension, assetIds: number[]) => invoke<void>("save_category_tag", { name, dimension, assetIds });
export const listClassificationRules = () => invoke<ClassificationRule[]>("list_classification_rules");
export const saveClassificationRule = (rule: ClassificationRule) => invoke<void>("save_classification_rule", { rule });
export const previewClassificationRule = (rule: ClassificationRule, request: AssetSearchRequest) => invoke<RuleCandidate[]>("preview_classification_rule", { rule, request });
export const applyClassificationRule = (rule: ClassificationRule, assetIds: number[]) => invoke<number>("apply_classification_rule", { rule, assetIds });
export const listClassificationBatches = () => invoke<ClassificationBatch[]>("list_classification_batches");
export const undoClassificationBatch = (batchId: number) => invoke<number>("undo_classification_batch", { batchId });
